### ISSUE TITLE
Request a viewing returning 500

### ISSUE THREAD

**Issue by williamspiro** [HubSpot/cms-custom-objects-example#45]
Something seems to have changed to cause the request a viewing feature to return a 500. I re-uploaded the main branch to make sure I did not have an old version. 

![Screen Shot 2020-10-07 at 6 20 43 PM](https://user-images.githubusercontent.com/35824747/95394170-ea764400-08c9-11eb-8a7c-771ca7d37e76.png)

https://tickets.theprofitpatch.com/property?property=25523266

cc @anthmatic

**Comment by williamspiro** [comment]
Looking at the logs of the function, I see
```
2020-10-07T22:18:26.613Z - SUCCESS - Execution Time: 331ms
{ body:
   { message:
      { name: 'Error',
        stack:
         'Error: Request failed with status code 401\n    at createError (/opt/nodejs/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/opt/nodejs/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/opt/nodejs/node_modules/axios/lib/adapters/http.js:236:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (_stream_readable.js:1220:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)',
        config: [Object],
        message: 'Request failed with status code 401' } },
  statusCode: 500 }
```

**Comment by anthmatic** [comment]
Looks like an auth error. Has the API key been rotated?

**Comment by williamspiro** [comment]
Sorry, should have looked a little closer 🤦

**Comment by williamspiro** [comment]
Thanks for looking @anthmatic
